#!/bin/bash

# Dependencies for STARCCM - centos
function install_chrony_yum() {
  yum -y install chrony
}

# Determine OS
source /etc/os-release
case ${ID} in
centos)
  install_chrony_yum
  systemctl enable chronyd
  ;;
*)
  juju-log -l 'ERROR' "Failed identifying supported OS from /etc/os-release, this is what I have: [$ID]"
  ;;
esac