#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

# This check for at least one ACTIVE infiniband port if ibstatus is installed.
# Start will be set in status: "blocked" if we detect problems.

  systemctl start chronyd
  status-set active "Ready"